database:
  local:
    path: "sqlite:///local_attendance_tracking.db"  # Đường dẫn tới local database
  online:
    user: "hrm"
    password: "hrm"
    host: "35.223.205.197"
    port: "5432"
    database: "attendance_tracking"

status:
  status: "OUT"

app:
  restart_time: "23:59"

image_path:
  image: "image_out"

camera_name:
  camera: "CAMERA_1"

capture_id: 'rtsp://pathtech:pathtech1@192.168.1.35:554/stream1'

distance_threshold: 0.6